vich_uploader:
    db_driver: orm

    mappings:
        voyages:
            uri_prefix: /images/voyages
            upload_destination: '%kernel.project_dir%/public/images/voyages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
